{% set min_python = "python >=3.8" %}
{% set version = "1.7.16" %}
{% set build_number = 0 %}
{% set min_python = "python >=3.8" %}

# some upstreams aren't ready for 3.11+
{% set dagster_default_epoch = "10" %}

# we need _some_ default in order to render
{% if dagster_epoch is not defined %}
  {% set dagster_epoch = dagster_default_epoch %}
{% endif %}

# airflow doesn't solve (even slowly) on python 3.11+
{% set dagster_core_only = dagster_epoch != dagster_default_epoch %}

# this allows for effectively using selectors downstream
{% set dagster_build_number = build_number * 100 + (dagster_epoch | int) %}
{% set dagster_python = "python >=3." ~ dagster_epoch ~ ",<3." ~ ((dagster_epoch | int) + 1) ~ ".0a0" %}

# "pendulum>=3,<4; python_version>='3.12'",
# "pendulum>=0.7.0,<4; python_version>='3.9' and python_version<'3.12'",
# "pendulum>=0.7.0,<3; python_version<'3.9'",  # https://github.com/dagster-io/dagster/issues/19500
{% set dagster_pendulum = "pendulum" ~ {
  "8":  " >=0.7.0,<3",
  "12": " >=3,<4",
}.get(dagster_epoch, " >=0.7.0,<4") %}

# "protobuf>=3.20.0,<5; python_version<'3.11'",  # min protobuf version to be compatible with both protobuf 3 and 4
# "protobuf>=4,<5; python_version>='3.11'",
{% set dagster_protobuf = "protobuf" ~ {
  "11": " >=4,<5",
  "12": " >=4,<5",
}.get(dagster_epoch, " >=3.20.0,<5") %}

# "universal_pathlib; python_version<'3.12'",
# "universal_pathlib>=0.2.0; python_version>='3.12'",
{% set dagster_universal_pathlib = "universal_pathlib" ~ {
  "12": ">=0.2.0",
}.get(dagster_epoch, "") %}

package:
  name: dagster-meta
  version: {{ version }}

source:
  # uses main version
  - folder: dagster-pipes
    url: https://pypi.io/packages/source/d/dagster-pipes/dagster-pipes-{{ version }}.tar.gz
    sha256: d78ab631c556966f8e35fc49b297d7a6a03d1546f692a85f024cba1c14fc628b

  - folder: dagster
    url: https://pypi.io/packages/source/d/dagster/dagster-{{ version }}.tar.gz
    sha256: a355be92503325061cc4c1e0401f63927c8e10f3b9b79b951886cd398056014a

  - folder: dagster-webserver
    url: https://pypi.io/packages/source/d/dagster-webserver/dagster-webserver-{{ version }}.tar.gz
    sha256: a1e0f85dbd79db3cd41038ef392351ecb7fa43fc20b919efa6cf57e8b799d10a

  - folder: dagit
    url: https://pypi.io/packages/source/d/dagit/dagit-{{ version }}.tar.gz
    sha256: 10068c085df194640d546fc26732caf9f1e27e21abcce1ed0fbcc4e22511089b

  - folder: dagster-graphql
    url: https://pypi.io/packages/source/d/dagster-graphql/dagster-graphql-{{ version }}.tar.gz
    sha256: 8c9e4c6f0d0de3d7cca1aa8fe10c8af15fd567e0f2eb6f6806f07a18c64286ce

  - folder: dagster-airflow
    url: https://pypi.io/packages/source/d/dagster-airflow/dagster-airflow-{{ version }}.tar.gz
    sha256: c56e93b46ef67049c9a4c53e58ad7591211a0327e7c98cef3729a72547eff232

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - {{ min_python }}
    - pip
  run:
    - {{ min_python }}

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: dagster-pipes
    build:
      version: {{ version }}
      noarch: python
      script: cd dagster-pipes && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
    test:
      requires:
        - {{ dagster_python }}
        - pip
      imports:
        - dagster_pipes
      commands:
        - pip check
    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-pipes
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-pipes/LICENSE
      summary: Toolkit for Dagster integrations with transform logic outside of Dagster

  - name: dagster
    build:
      number: {{ dagster_build_number }}
      noarch: python
      version: {{ version }}
      entry_points:
        - dagster = dagster.cli:main
        - dagster-daemon = dagster.daemon.cli:main
      script: cd dagster && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ dagster_pendulum }}
        - {{ dagster_protobuf }}
        - {{ dagster_universal_pathlib }}
        - {{ min_python }}
        - {{ pin_subpackage("dagster-pipes", max_pin="x.x.x") }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - click >=5.0
        - coloredlogs >=6.1,<=14.0
        - croniter >=0.3.34
        - docstring_parser
        - filelock
        - grpcio >=1.44.0,<1.65.0
        - grpcio-health-checking >=1.44.0,<1.65.0
        - jinja2
        - packaging >=20.9
        - psutil >=1.0
        - pydantic >1.10.0,!=1.10.7,<3
        - python-dotenv
        - pytz
        - pywin32-on-windows
        - pyyaml >=5.1
        - requests
        - rich
        - setuptools
        - sqlalchemy >=1.0,<3
        - structlog
        - tabulate
        - tomli <3
        - toposort >=1.0
        - tqdm <5
        - typing_extensions >=4.4.0,<5
        - watchdog >=0.8.3
      run_constrained:
        - {{ dagster_python }}
        - pywin32 !=226
    test:
      requires:
        - {{ dagster_python }}
        - pip
      imports:
        - dagster
        - dagster.api
        - dagster.check
        - dagster.cli
        - dagster.config
        - dagster.core.definitions
        - dagster.core.events
        - dagster.core.execution
        - dagster.core.executor
        - dagster.core.instance
        - dagster.core.launcher
        - dagster.core.run_coordinator
        - dagster.core.scheduler
        - dagster.core.selector
        - dagster.core.snap
        - dagster.core.storage
        - dagster.core.system_config
        - dagster.core.types
        - dagster.core.workspace
        - dagster.daemon
        - dagster.grpc
        - dagster.loggers
        - dagster.seven
        - dagster.utils
      commands:
        - pip check
        - dagster --help
        - dagster-daemon --help
    about:
      home: https://github.com/dagster-io/dagster
      license: Apache-2.0
      license_family: APACHE
      summary: The data orchestration platform built for productivity.
      doc_url: https://dagster.readthedocs.io
      license_file: dagster/LICENSE
      description: |
        Dagster lets you define pipelines in terms of the data flow between reusable, logical components,
        then test locally and run anywhere. With a unified view of pipelines and the assets they produce,
        Dagster can schedule and orchestrate Pandas, Spark, SQL, or anything else that Python can invoke.

        Dagster is designed for data platform engineers, data engineers, and full-stack data scientists.
        Building a data platform with Dagster makes your stakeholders more independent and your systems
        more robust. Developing data pipelines with Dagster makes testing easier and deploying faster.

  - name: dagster-webserver
    build:
      version: {{ version }}
      noarch: python
      script: cd dagster-webserver && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      entry_points:
        - dagster-webserver = dagster_webserver.cli:main
        - dagster-webserver-debug = dagster_webserver.debug:main
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
        - {{ pin_subpackage("dagster-graphql", max_pin="x.x.x") }}
        - {{ pin_subpackage("dagster", max_pin="x.x.x") }}
        - click >=7.0,<9.0
        - starlette !=0.36.0
        - uvicorn-standard
    test:
      requires:
        - {{ dagster_python }}
        - pip
      imports:
        - dagster_webserver
      commands:
        - pip check
        - dagster-webserver --help
        - dagster-webserver-debug --help
    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-webserver
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-webserver/LICENSE
      summary: Web UI for dagster.

  - name: dagster-graphql
    build:
      version: {{ version }}
      noarch: python
      entry_points:
        - dagster-graphql = dagster_graphql.cli:main
      script:
        - cd dagster-graphql && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
        - {{ pin_subpackage("dagster", max_pin="x.x.x") }}
        - gql-with-requests >=3.0.0,<4.0.0
        - graphene >=3,<4
        - requests
        - starlette
    test:
      requires:
        - {{ dagster_python }}
        - pip
      imports:
        - dagster_graphql
        - dagster_graphql.client
        - dagster_graphql.schema
      commands:
        - dagster-graphql --help
        - pip check
    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-graphql/LICENSE
      summary: The GraphQL frontend to python dagster.

  - name: dagit
    build:
      noarch: python
      version: {{ version }}
      entry_points:
        - dagit = dagster_webserver.cli:main
        - dagit-debug = dagster_webserver.debug:main
      script: cd dagit && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
        - {{ pin_subpackage("dagster-webserver", max_pin="x.x.x") }}
    test:
      requires:
        - {{ dagster_python }}
        - pip
      imports:
        - dagit
      commands:
        - pip check
        - dagit --help
    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagit
      license: Apache-2.0
      license_family: APACHE
      license_file: dagit/LICENSE
      summary: Dagster UI

{% if not dagster_core_only %}
  - name: dagster-airflow
    build:
      noarch: python
      version: {{ version }}
      script:
        - cd dagster-airflow && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - {{ min_python }}
        - pip
      run:
        - {{ min_python }}
        - {{ pin_subpackage("dagster", max_pin="x.x.x") }}
        - docker-py >=5.0.3,<6
        - lazy-object-proxy
        - python >=3.8
        - setuptools <71.0.0
        # docker version pinned above requires this but has no pin
        - urllib3 <2
    test:
      requires:
        - {{ dagster_python }}
        - pip
        - apache-airflow-providers-docker
        # otherwise `swagger-ui-bundle 0.0.6 is not supported on this platform`
        - swagger-ui-bundle >=1.1.0
      imports:
        - dagster_airflow
      commands:
        - pip check
    about:
      home: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow
      license: Apache-2.0
      license_family: APACHE
      license_file: dagster-airflow/LICENSE
      summary: Airflow plugin for Dagster
{% endif %}

about:
  home: https://github.com/dagster-io
  summary: The data orchestration platform built for productivity.
  license: Apache-2.0
  license_family: APACHE
  license_file: dagster/LICENSE
  doc_url: https://dagster.readthedocs.io
  description: >-
    Dagster is a system for building modern data applications. Combining an elegant programming model and beautiful tools, Dagster allows infrastructure engineers, data engineers, and data scientists to seamlessly collaborate to process and produce the trusted, reliable data needed in today's world.

extra:
  feedstock-name: dagster
  recipe-maintainers:
    - xhochy
    - bollwyvl
    - mgasner
