# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  # source-of-truth
  version: "1.13.4"
  # derived
  patch_version: ${{ (version | split('.'))[2] }}
  dagster_libs_version: 0.29.${{ patch_version }}
  # convenience
  pip_install: -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

recipe:
  name: dagster-meta
  version: ${{ version }}

build:
  noarch: python
  number: 0

outputs:
  # deps of dagster
  - package:
      name: dagster-pipes
    source:
      url: https://pypi.org/packages/source/d/dagster-pipes/dagster_pipes-${{ version }}.tar.gz
      sha256: a9b9965e1eff5dc13dd6797628ae38d56143eed6174de4b7de0f5b54deb596fa
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_pipes
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-pipes
      license: Apache-2.0
      license_file: LICENSE
      summary: Toolkit for Dagster integrations with transform logic outside of Dagster

  - package:
      name: dagster-shared
    source:
      url: https://pypi.org/packages/source/d/dagster-shared/dagster_shared-${{ version }}.tar.gz
      sha256: 4116acb5a78aac852027e43ebad914471e98304fead7992f04c3baec39fa0d2d
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - packaging >=20.9
        - platformdirs
        - pydantic >=2,<3.0.0
        - python >=${{ python_min }}
        - pyyaml >=5.1
        - tomlkit
        - typing_extensions >=4.11.0,<5
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_shared
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/librariees/dagster-shared
      license: Apache-2.0
      license_file: LICENSE
      summary: Shared code between dagster and dagster-dg.

  # dagster itself
  - package:
      name: dagster
    source:
      url: https://pypi.org/packages/source/d/dagster/dagster-${{ version }}.tar.gz
      sha256: 7214234c4cf257a276e01b662e770bc69ab5baeff2755487b2f494d9f1c0b532
    build:
      number: 0
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster = dagster._cli:main
          - dagster-daemon = dagster._daemon.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-pipes", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - antlr-python-runtime
        - click >=5.0,<9.0
        - coloredlogs >=6.1,<=14.0
        - docstring_parser
        - filelock
        - jinja2
        - psutil >=1.0
        - python >=${{ python_min }}
        - python-dotenv
        - python-tzdata
        - pytz
        - pywin32-on-windows
        - requests
        - rich
        - six
        - sqlalchemy >=1.0,<3
        - structlog
        - tabulate
        - tomli <3
        - toposort >=1.0
        - tqdm <5
        - watchdog >=0.8.3,<7
        - if: match(python_min, "<3.13")
          then: grpcio >=1.44.0
        - if: match(python_min, ">=3.13")
          then: grpcio >=1.66.2
        - if: match(python_min, "<3.13")
          then: grpcio-health-checking >=1.44.0
        - if: match(python_min, ">=3.13")
          then: grpcio-health-checking >=1.66.2
        - if: match(python_min, "<3.11")
          then: protobuf >=3.20.0,<7
        - if: match(python_min, ">=3.11")
          then: protobuf >=4,<7
        - if: match(python_min, ">=3.12")
          then: universal_pathlib >=0.2.0
        - if: match(python_min, "<3.12")
          then: universal_pathlib
      run_constraints:
        - python ${{ python_min }}.*
        - pywin32 !=226
    tests:
      - python:
          imports:
            - dagster
            - dagster.components.core
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagster --help
          - dagster-daemon --help
    about:
      homepage: https://github.com/dagster-io/dagster
      license: Apache-2.0
      summary: The data orchestration platform built for productivity.
      documentation: https://dagster.readthedocs.io
      license_file: LICENSE
      description: |
        Dagster lets you define pipelines in terms of the data flow between reusable, logical components,
        then test locally and run anywhere. With a unified view of pipelines and the assets they produce,
        Dagster can schedule and orchestrate Pandas, Spark, SQL, or anything else that Python can invoke.

        Dagster is designed for data platform engineers, data engineers, and full-stack data scientists.
        Building a data platform with Dagster makes your stakeholders more independent and your systems
        more robust. Developing data pipelines with Dagster makes testing easier and deploying faster.

  # other things that use the main `version`
  - package:
      name: create-dagster
    source:
      url: https://pypi.org/packages/source/c/create-dagster/create_dagster-${{ version }}.tar.gz
      sha256: 8e809ac1336865f06b6a8dadabe421e8b8fc72658f9348ed7e9a0c95eed0b3b5
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - create-dagster = create_dagster.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: create_dagster
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - create-dagster --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/create-dagster
      license: Apache-2.0
      license_file: LICENSE
      summary: CLI for creating a new dg project or workspace.

  - package:
      name: dagster-cloud-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-cloud-cli/dagster_cloud_cli-${{ version }}.tar.gz
      sha256: e44cab102edd31de889dd5664dd34572cab0cdb60f91c9a2d63696b5b1221be4
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-cloud = dagster_cloud_cli.entrypoint:app
          - dagster-plus = dagster_cloud_cli.entrypoint:app
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click
        - github3.py
        - jinja2
        - packaging >=20.9
        - python >=${{ python_min }}
        - pyyaml >=5.1
        - questionary
        - requests
        - setuptools
        - typer >=0.15.0
        - validators
        - if: match(python_min, "<3.11")
          then: tomli >=1.1.0
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_cloud_cli
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagster-cloud --help
          - dagster-plus --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-cloud-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Command line interface for Dagster Cloud

  - package:
      name: dagster-dg-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-cli/dagster_dg_cli-${{ version }}.tar.gz
      sha256: 1f0cb7a9fa633e38755d3922d711be34a3853221df7ca0b711d1e92816835bb0
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dg = dagster_dg_cli.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-cloud-cli", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-rest-resources", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
        - typer
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_dg_cli
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dg --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Experimental API for scaffolding Dagster projects and components. Includes the dg CLI tool.

  - package:
      name: dagster-dg-core
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-core/dagster_dg_core-${{ version }}.tar.gz
      sha256: dff10d4723972881cb1d89a0e321b2a1b1fababd94004eba1a6abc89e8250319
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-cloud-cli", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click >=8,<9
        - click-aliases
        - gql-with-requests
        - jinja2
        - jsonschema
        - markdown
        - packaging
        - python >=${{ python_min }}
        - python-dotenv
        - pyyaml >=5.1
        - rich
        - setuptools
        - tomlkit <0.13.3
        - typer >=0.15.1,<1.0
        - typing_extensions >=4.4.0,<5
        - watchdog
        - yaspin
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_dg_core
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-core
      license: Apache-2.0
      license_file: LICENSE
      summary: Core libraries for the dagster-dg-cli and create-dagster packages.

  - package:
      name: dagster-graphql
    source:
      url: https://pypi.org/packages/source/d/dagster-graphql/dagster_graphql-${{ version }}.tar.gz
      sha256: ef8d0d592c3c866222f7bedff0212fd518bda05f815b34aee2bf82009ea3276d
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-graphql = dagster_graphql.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - gql-with-requests >=3,<5
        - graphene >=3,<4
        - python >=${{ python_min }}
        - requests
        - starlette
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports:
            - dagster_graphql
            - dagster_graphql.client
            - dagster_graphql.schema
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagster-graphql --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql
      license: Apache-2.0
      license_file: LICENSE
      summary: The GraphQL frontend to python dagster.

  - package:
      name: dagster-rest-resources
      version: ${{ dagster_libs_version }}
    source:
      url: https://pypi.org/packages/source/d/dagster-rest-resources/dagster_rest_resources-${{ dagster_libs_version }}.tar.gz
      sha256: 873de3162dd97b47ab442e7f226827311da418fee7e66e6411de5b2ff48a52bf
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - httpx >=0.27.0
        - pydantic >=2.12.5
        - python >=${{ python_min }}
    tests:
      - python:
          imports: dagster_rest_resources
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-rest-resources
      license: Apache-2.0
      license_file: LICENSE
      summary: Dagster functionality as REST-style resources

  - package:
      name: dagster-webserver
    source:
      url: https://pypi.org/packages/source/d/dagster-webserver/dagster_webserver-${{ version }}.tar.gz
      sha256: 29da6bf1ce8893d3f53eda2be0edfe8eb0e6ec5cc44139f2df78f0cb3e825331
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-webserver = dagster_webserver.cli:main
          - dagster-webserver-debug = dagster_webserver.debug:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-graphql", upper_bound="x.x.x") }}
        - click >=7.0,<9.0
        - python >=${{ python_min }}
        - starlette !=0.36.0
        - uvicorn-standard
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_webserver
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagster-webserver --help
          - dagster-webserver-debug --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-webserver
      license: Apache-2.0
      license_file: LICENSE
      summary: Web UI for dagster.

  - package:
      name: dagit
    source:
      url: https://pypi.org/packages/source/d/dagit/dagit-${{ version }}.tar.gz
      sha256: 808176a83161d430c2678de9eb18a65a2b18d1a9c02ec05fe4ccca74bd85e6c8
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagit = dagster_webserver.cli:main
          - dagit-debug = dagster_webserver.debug:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-webserver", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagit
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagit --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagit
      license: Apache-2.0
      license_file: LICENSE
      summary: Dagster UI

  - package:
      name: dagster-airflow
    source:
      url: https://pypi.org/packages/source/d/dagster-airflow/dagster_airflow-${{ version }}.tar.gz
      sha256: 5840528a5865226b54dfe090feb89d72398f710b87bbd362a08d99c2fd12a536
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - lazy-object-proxy
        - pendulum
        - python >=${{ python_min }}
        - setuptools <71.0.0
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      # not-yet-available-on-conda-forge
      - if: not match(python_min, ">=3.13")
        then:
          requirements:
            run:
              - pip
              # errors with:
              ##  >>> from airflow.hooks.base_hook import BaseHook
              ##  ModuleNotFoundError: No module named 'airflow.hooks.base_hook'
              - airflow <3
              # apache-airflow-providers-fab 2.4.4 has requirement apache-airflow>=3.0.2, but you have apache-airflow 2.11.0.
              - apache-airflow-providers-fab <2
              - python ${{ python_min }}.*
          script:
            - pip check
            - python -c "import dagster_airflow"
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow
      license: Apache-2.0
      license_file: LICENSE
      summary: Airflow plugin for Dagster

about:
  homepage: https://github.com/dagster-io
  summary: The data orchestration platform built for productivity.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://dagster.readthedocs.io
  description: >-
    Dagster is a system for building modern data applications. Combining an elegant programming model and beautiful tools, Dagster allows infrastructure engineers, data engineers, and data scientists to seamlessly collaborate to process and produce the trusted, reliable data needed in today's world.

extra:
  feedstock-name: dagster
  recipe-maintainers:
    - xhochy
    - bollwyvl
    - mgasner
