# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  # source-of-truth
  version: 1.10.21
  build_number: 0
  # derived
  dagster_python: python >=${{ python_min }},<3.13
  dagster_epoch: ${{ dagster_epoch | default("10") }}
  dagster_epoch_python: |-
    python 3.${{ dagster_epoch | default("10") }}.*
  dagster_build_number: ${{ (build_number | int) * 100 + (dagster_epoch | int) }}
  # convenience
  pip_install: -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

recipe:
  name: dagster-meta
  version: ${{ version }}

build:
  noarch: python
  number: ${{ build_number }}

outputs:
  # deps of dagster
  - package:
      name: dagster-pipes
    source:
      url: https://pypi.org/packages/source/d/dagster-pipes/dagster_pipes-${{ version }}.tar.gz
      sha256: 8d68982701836538b7d731b4829f8201bee87b1d381b306278f9aee494bc7501
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
    tests:
      - python:
          pip_check: true
          imports: dagster_pipes
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-pipes
      license: Apache-2.0
      license_file: LICENSE
      summary: Toolkit for Dagster integrations with transform logic outside of Dagster

  - package:
      name: dagster-shared
    source:
      url: https://pypi.org/packages/source/d/dagster-shared/dagster_shared-${{ version }}.tar.gz
      sha256: 0e6a68d8e14456daa15e636857ce4f03996487dab80a826d8e5d270d053b6e11
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
        - pyyaml >=5.1
        - packaging >=20.9
        - pydantic >=2,<3.0.0
        - tomlkit
        - typing_extensions >=4.11.0,<5
    tests:
      - python:
          pip_check: true
          imports: dagster_shared
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/librariees/dagster-shared
      license: Apache-2.0
      license_file: LICENSE
      summary: Shared code between dagster and dagster-dg.

  # dagster itself
  - package:
      name: dagster
    source:
      url: https://pypi.org/packages/source/d/dagster/dagster-${{ version }}.tar.gz
      sha256: 14e4baa243b51cc6d5b69be1f65720da897729b923860bb04ae009ea534512b6
    build:
      number: ${{ dagster_build_number }}
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster = dagster.cli:main
          - dagster-daemon = dagster.daemon.cli:main
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - if: dagster_epoch == "12"
          then: universal_pathlib >=0.2.0
          else: universal_pathlib
        - if: dagster_epoch in ["11", "12"]
          then: protobuf >=4,<6
          else: protobuf >=3.20.0,<6
        - ${{ dagster_python }}
        - ${{ pin_subpackage("dagster-pipes", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - antlr-python-runtime
        - click >=5.0,<8.2
        - coloredlogs >=6.1,<=14.0
        - docstring_parser
        - filelock
        - grpcio >=1.44.0
        - grpcio-health-checking >=1.44.0
        - jinja2
        - psutil >=1.0
        - python-dotenv
        - pytz
        - pywin32-on-windows
        - requests
        - rich
        - setuptools
        - six
        - sqlalchemy >=1.0,<3
        - structlog
        - tabulate
        - tomli <3
        - toposort >=1.0
        - tqdm <5
        - tzdata
        - watchdog >=0.8.3,<6
      run_constraints:
        - ${{ dagster_epoch_python }}
        - pywin32 !=226
    tests:
      - python:
          pip_check: true
          imports:
            - dagster
            - dagster.api
            - dagster.check
            - dagster.cli
            - dagster.config
            - dagster.core.definitions
            - dagster.core.events
            - dagster.core.execution
            - dagster.core.executor
            - dagster.core.instance
            - dagster.core.launcher
            - dagster.core.run_coordinator
            - dagster.core.scheduler
            - dagster.core.selector
            - dagster.core.snap
            - dagster.core.storage
            - dagster.core.system_config
            - dagster.core.types
            - dagster.core.workspace
            - dagster.daemon
            - dagster.grpc
            - dagster.loggers
            - dagster.seven
            - dagster.utils
      - script:
          - dagster --help
          - dagster-daemon --help
    about:
      homepage: https://github.com/dagster-io/dagster
      license: Apache-2.0
      summary: The data orchestration platform built for productivity.
      documentation: https://dagster.readthedocs.io
      license_file: LICENSE
      description: |
        Dagster lets you define pipelines in terms of the data flow between reusable, logical components,
        then test locally and run anywhere. With a unified view of pipelines and the assets they produce,
        Dagster can schedule and orchestrate Pandas, Spark, SQL, or anything else that Python can invoke.

        Dagster is designed for data platform engineers, data engineers, and full-stack data scientists.
        Building a data platform with Dagster makes your stakeholders more independent and your systems
        more robust. Developing data pipelines with Dagster makes testing easier and deploying faster.

  # other things that use the main `version`
  - package:
      name: create-dagster
    source:
      url: https://pypi.org/packages/source/c/create-dagster/create_dagster-${{ version }}.tar.gz
      sha256: 4aef4893eb18c864f89d539047b550c16cebbfaa273c8ddd45880a31283b47cb
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - create-dagster = create_dagster.cli:main
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - ${{ dagster_python }}
    tests:
      - python:
          imports: create_dagster
          pip_check: true
      - script:
          - create-dagster --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/create-dagster
      license: Apache-2.0
      license_file: LICENSE
      summary: CLI for creating a new dg project or workspace.

  - package:
      name: dagster-cloud-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-cloud-cli/dagster_cloud_cli-${{ version }}.tar.gz
      sha256: 7debc51430f883a161762007bf7af41aa7ba58267959df1a73d436297c9cf93f
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-cloud = dagster_cloud_cli.entrypoint:app
          - dagster-plus = dagster_cloud_cli.entrypoint:app
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click <8.2
        - github3.py
        - jinja2
        - packaging >=20.9
        - pyyaml >=5.1
        - questionary
        - requests
        - typer >=0.4.1
    tests:
      - python:
          pip_check: true
          imports:
            - dagster_cloud_cli
      - requirements:
          run:
            - ${{ dagster_epoch_python }}
        script:
          - dagster-cloud --help
          - dagster-plus --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-cloud-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Command line interface for Dagster Cloud

  - package:
      name: dagster-dg-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-cli/dagster_dg_cli-${{ version }}.tar.gz
      sha256: 48af8d08f71cccd00633679c63943e2076a3ec591b06fa204175384108791b43
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dg = dagster_dg_cli.cli:main
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - ${{ dagster_python }}
    tests:
      - python:
          imports: dagster_dg_cli
          pip_check: true
      - script:
          - dg --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Experimental API for scaffolding Dagster projects and components. Includes the dg CLI tool.

  - package:
      name: dagster-dg-core
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-core/dagster_dg_core-${{ version }}.tar.gz
      sha256: dbdb253f0c2af081cfef5872a755121332a4146161880ccfda0b50b9fb620ceb
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-cloud-cli", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - ${{ dagster_python }}
        - click >=8,<8.2
        - click-aliases
        - gql-with-requests
        - jinja2
        - jsonschema
        - markdown
        - packaging
        - python-dotenv
        - pyyaml >=5.1
        - rich
        - setuptools
        - tomlkit <0.13.3
        - typer <0.17.0
        - typing_extensions >=4.4.0,<5
        - watchdog
        - yaspin
    tests:
      - python:
          imports: dagster_dg_core
          pip_check: true
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-core
      license: Apache-2.0
      license_file: LICENSE
      summary: Core libraries for the dagster-dg-cli and create-dagster packages.

  - package:
      name: dagster-graphql
    source:
      url: https://pypi.org/packages/source/d/dagster-graphql/dagster_graphql-${{ version }}.tar.gz
      sha256: 6a5b9e07df572b1df8a6259d4743bf1871faaac4bb7bf41bec3fcffec901daab
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-graphql = dagster_graphql.cli:main
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - gql-with-requests >=3.0.0,<4.0.0
        - graphene >=3,<4
        - requests
        - starlette
    tests:
      - python:
          pip_check: true
          imports:
            - dagster_graphql
            - dagster_graphql.client
            - dagster_graphql.schema
      - requirements:
          run:
            - ${{ dagster_epoch_python }}
        script:
          - dagster-graphql --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql
      license: Apache-2.0
      license_file: LICENSE
      summary: The GraphQL frontend to python dagster.

  - package:
      name: dagster-webserver
    source:
      url: https://pypi.org/packages/source/d/dagster-webserver/dagster_webserver-${{ version }}.tar.gz
      sha256: 036b619a5b0f4cd28dbee68fe845b67547f73df621354f7b5c62083f5506e373
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-webserver = dagster_webserver.cli:main
          - dagster-webserver-debug = dagster_webserver.debug:main
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
        - ${{ pin_subpackage("dagster-graphql", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - click >=7.0,<9.0
        - starlette !=0.36.0
        - uvicorn-standard
    tests:
      - python:
          pip_check: true
          imports: dagster_webserver
      - requirements:
          run:
            - ${{ dagster_epoch_python }}
        script:
          - dagster-webserver --help
          - dagster-webserver-debug --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-webserver
      license: Apache-2.0
      license_file: LICENSE
      summary: Web UI for dagster.

  - package:
      name: dagit
    source:
      url: https://pypi.org/packages/source/d/dagit/dagit-${{ version }}.tar.gz
      sha256: 23fe4798ab33320994bee37ca18acc0af953708b9f219d979f9073aab3ed6b58
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagit = dagster_webserver.cli:main
          - dagit-debug = dagster_webserver.debug:main
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
        - ${{ pin_subpackage("dagster-webserver", upper_bound="x.x.x") }}
    tests:
      - python:
          pip_check: true
          imports: dagit
      - requirements:
          run:
            - ${{ dagster_epoch_python }}
        script:
          - dagit --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagit
      license: Apache-2.0
      license_file: LICENSE
      summary: Dagster UI

  - package:
      name: dagster-airflow
    source:
      url: https://pypi.org/packages/source/d/dagster-airflow/dagster_airflow-${{ version }}.tar.gz
      sha256: ca2a20870f2579c7dc06e4f34eaed1a39d4900a399f67bc85429d3fd51e995fa
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - ${{ dagster_python }}
        - pip
        - setuptools
      run:
        - ${{ dagster_python }}
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - lazy-object-proxy
        - pendulum
        - setuptools <71.0.0
    tests:
      - requirements:
          run:
            - pip
            # errors with:
            ##  >>> from airflow.hooks.base_hook import BaseHook
            ##  ModuleNotFoundError: No module named 'airflow.hooks.base_hook'
            - airflow <3
        script:
          - pip check
          - python -c "import dagster_airflow"
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow
      license: Apache-2.0
      license_file: LICENSE
      summary: Airflow plugin for Dagster

about:
  homepage: https://github.com/dagster-io
  summary: The data orchestration platform built for productivity.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://dagster.readthedocs.io
  description: >-
    Dagster is a system for building modern data applications. Combining an elegant programming model and beautiful tools, Dagster allows infrastructure engineers, data engineers, and data scientists to seamlessly collaborate to process and produce the trusted, reliable data needed in today's world.

extra:
  feedstock-name: dagster
  recipe-maintainers:
    - xhochy
    - bollwyvl
    - mgasner
