# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  # source-of-truth
  version: "1.13.25"
  # derived
  patch_version: ${{ (version | split('.'))[2] }}
  dagster_libs_version: 0.29.${{ patch_version }}
  # convenience
  pip_install: |-
    -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies

recipe:
  name: dagster-meta
  version: ${{ version }}

build:
  noarch: python
  number: 0

outputs:
  # deps of dagster
  - package:
      name: dagster-pipes
    source:
      url: https://pypi.org/packages/source/d/dagster-pipes/dagster_pipes-${{ version }}.tar.gz
      sha256: b8d18fa37936f91892ee6e49532ab6309e0e10897b9fd696f43f4306871050eb
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_pipes/**
            - dagster_pipes-${{ version }}.dist-info/**
      - python:
          imports: dagster_pipes
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-pipes
      license: Apache-2.0
      license_file: LICENSE
      summary: Toolkit for Dagster integrations with transform logic outside of Dagster

  - package:
      name: dagster-shared
    source:
      url: https://pypi.org/packages/source/d/dagster-shared/dagster_shared-${{ version }}.tar.gz
      sha256: adc3701f61e4a2110d27ff298001083696506453dfae18f7264c5f73326ba41d
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - packaging >=20.9
        - platformdirs
        - pydantic >=2,<3.0.0
        - python >=${{ python_min }}
        - pyyaml >=5.1
        - tomlkit
        - typing_extensions >=4.11.0,<5
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_shared/**
            - dagster_shared-${{ version }}.dist-info/**
      - python:
          imports: dagster_shared
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/librariees/dagster-shared
      license: Apache-2.0
      license_file: LICENSE
      summary: Shared code between dagster and dagster-dg.

  # dagster itself
  - package:
      name: dagster
    source:
      url: https://pypi.org/packages/source/d/dagster/dagster-${{ version }}.tar.gz
      sha256: 27b4bd21c9f97df40b660a828da5ac585474cfa1f8268fb9a5e62b3055bf7afe
    build:
      number: 0
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster = dagster._cli:main
          - dagster-daemon = dagster._daemon.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-pipes", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - antlr-python-runtime <4.14
        - click >=5.0,<9.0
        - coloredlogs >=6.1,<=14.0
        - docstring_parser
        - filelock
        - jinja2
        - psutil >=1.0
        - python >=${{ python_min }}
        - python-dotenv
        - python-tzdata
        - pytz
        - pywin32-on-windows
        - requests
        - rich
        - six
        - sqlalchemy >=1.0,<3
        - structlog
        - tabulate
        - tomli <3
        - toposort >=1.0
        - tqdm <5
        - watchdog >=0.8.3,<7
        - if: match(python_min, "<3.13")
          then: grpcio >=1.44.0
        - if: match(python_min, ">=3.13")
          then: grpcio >=1.66.2
        - if: match(python_min, "<3.13")
          then: grpcio-health-checking >=1.44.0,<1.82
        - if: match(python_min, ">=3.13")
          then: grpcio-health-checking >=1.66.2,<1.82
        - if: match(python_min, ">=3.11")
          then: protobuf >=4,<7
        - if: match(python_min, ">=3.12")
          then: universal_pathlib >=0.2.0
        - if: match(python_min, "<3.12")
          then: universal_pathlib
      run_constraints:
        - python ${{ python_min }}.*
        - pywin32 !=226
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster/**
            - dagster-${{ version }}.dist-info/**
      - python:
          imports:
            - dagster
            - dagster.components.core
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagster --help
          - dagster-daemon --help
    about:
      homepage: https://github.com/dagster-io/dagster
      license: Apache-2.0
      summary: The data orchestration platform built for productivity.
      documentation: https://dagster.readthedocs.io
      license_file: LICENSE
      description: |
        Dagster lets you define pipelines in terms of the data flow between reusable, logical components,
        then test locally and run anywhere. With a unified view of pipelines and the assets they produce,
        Dagster can schedule and orchestrate Pandas, Spark, SQL, or anything else that Python can invoke.

        Dagster is designed for data platform engineers, data engineers, and full-stack data scientists.
        Building a data platform with Dagster makes your stakeholders more independent and your systems
        more robust. Developing data pipelines with Dagster makes testing easier and deploying faster.

  # other things that use the main `version`
  - package:
      name: create-dagster
    source:
      url: https://pypi.org/packages/source/c/create-dagster/create_dagster-${{ version }}.tar.gz
      sha256: a7ef6fef58c15e2c546b493f254071d7ab429be58d680749144bb56d7a644bf1
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - create-dagster = create_dagster.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - create_dagster/**
            - create_dagster-${{ version }}.dist-info/**
      - python:
          imports: create_dagster
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - create-dagster --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/create-dagster
      license: Apache-2.0
      license_file: LICENSE
      summary: CLI for creating a new dg project or workspace.

  - package:
      name: dagster-cloud-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-cloud-cli/dagster_cloud_cli-${{ version }}.tar.gz
      sha256: b7904a6601cadbe61e9484d958c06a2e178f1eebf2da74cbaef4a9f8b15021a2
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-cloud = dagster_cloud_cli.entrypoint:app
          - dagster-plus = dagster_cloud_cli.entrypoint:app
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click
        - github3.py
        - jinja2
        - packaging >=20.9
        - python >=${{ python_min }}
        - pyyaml >=5.1
        - questionary
        - requests
        - setuptools
        - typer >=0.15.0
        - validators
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_cloud_cli/**
            - dagster_cloud_cli-${{ version }}.dist-info/**
      - python:
          imports: dagster_cloud_cli
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagster-cloud --help
          - dagster-plus --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-cloud-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Command line interface for Dagster Cloud

  - package:
      name: dagster-dg-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-cli/dagster_dg_cli-${{ version }}.tar.gz
      sha256: 39e4f9aa86d6ed94be8f651691eba6b0a919577e865ee45de40e60afe4da40e4
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dg = dagster_dg_cli.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-cloud-cli", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-rest-resources", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
        - requests
        - typer
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_dg_cli/**
            - dagster_dg_cli-${{ version }}.dist-info/**
      - python:
          imports: dagster_dg_cli
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dg --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Experimental API for scaffolding Dagster projects and components. Includes the dg CLI tool.

  - package:
      name: dagster-dg-core
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-core/dagster_dg_core-${{ version }}.tar.gz
      sha256: f1ef13f30bd8740f5a9708c1346a821e94884c5045e2aefb44a53f065cdfc453
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-cloud-cli", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click >=8,<9
        - click-aliases
        - gql-with-requests
        - jinja2
        - jsonschema
        - markdown
        - packaging
        - python >=${{ python_min }}
        - python-dotenv
        - pyyaml >=5.1
        - rich
        - setuptools
        - tomlkit <0.16,!=0.13.3
        - typer >=0.15.1,<1.0
        - typing_extensions >=4.4.0,<5
        - watchdog
        - yaspin
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_dg_core/**
            - dagster_dg_core-${{ version }}.dist-info/**
      - python:
          imports: dagster_dg_core
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-core
      license: Apache-2.0
      license_file: LICENSE
      summary: Core libraries for the dagster-dg-cli and create-dagster packages.

  - package:
      name: dagster-graphql
    source:
      url: https://pypi.org/packages/source/d/dagster-graphql/dagster_graphql-${{ version }}.tar.gz
      sha256: 94a52332761d812127b0ee87c090d9f024f357b5928359b6f1f1197ff0bac024
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-graphql = dagster_graphql.cli:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - gql-with-requests >=3,<5
        - graphene >=3,<4
        - python >=${{ python_min }}
        - requests
        - starlette
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_graphql/**
            - dagster_graphql-${{ version }}.dist-info/**
      - python:
          imports:
            - dagster_graphql
            - dagster_graphql.client
            - dagster_graphql.schema
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagster-graphql --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql
      license: Apache-2.0
      license_file: LICENSE
      summary: The GraphQL frontend to python dagster.

  - package:
      name: dagster-rest-resources
      version: ${{ dagster_libs_version }}
    source:
      url: https://pypi.org/packages/source/d/dagster-rest-resources/dagster_rest_resources-${{ dagster_libs_version }}.tar.gz
      sha256: 04edacc25828c853859df000540384117d30dc66c70bfbcf4b2f898b19c4b1ec
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - httpx >=0.27.0
        - pydantic >=2.12.5
        - python >=${{ python_min }}
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_rest_resources/**
            - dagster_rest_resources-${{ version }}.dist-info/**
      - python:
          imports: dagster_rest_resources
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-rest-resources
      license: Apache-2.0
      license_file: LICENSE
      summary: Dagster functionality as REST-style resources

  - package:
      name: dagster-webserver
    source:
      url: https://pypi.org/packages/source/d/dagster-webserver/dagster_webserver-${{ version }}.tar.gz
      sha256: f62f8435b73dbbc0a17b0147cb24336fcf42521468de80468d692066dd00fa23
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-webserver = dagster_webserver.cli:main
          - dagster-webserver-debug = dagster_webserver.debug:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-graphql", upper_bound="x.x.x") }}
        - click >=7.0,<9.0
        - python >=${{ python_min }}
        - starlette !=0.36.0
        - uvicorn-standard
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_webserver/**
            - dagster_webserver-${{ version }}.dist-info/**
      - python:
          imports: dagster_webserver
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagster-webserver --help
          - dagster-webserver-debug --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-webserver
      license: Apache-2.0
      license_file: LICENSE
      summary: Web UI for dagster.

  - package:
      name: dagit
    source:
      url: https://pypi.org/packages/source/d/dagit/dagit-${{ version }}.tar.gz
      sha256: b2831b3a6304beda08ace1a2b6f0fdd079179c42c9fd3fbb882cf2ab2ac64dd9
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagit = dagster_webserver.cli:main
          - dagit-debug = dagster_webserver.debug:main
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster-webserver", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagit/**
            - dagit-${{ version }}.dist-info/**
      - python:
          imports: dagit
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagit --help
          - dagit-debug --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagit
      license: Apache-2.0
      license_file: LICENSE
      summary: Dagster UI

  - package:
      name: dagster-airflow
    source:
      url: https://pypi.org/packages/source/d/dagster-airflow/dagster_airflow-${{ version }}.tar.gz
      sha256: d6bb8ff513bb1f85e9f28e7b9bd929d221bbf1fb7457a1d2c1cfe4f14ca07da9
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - hatchling >=1.19.0
        - pip
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - lazy-object-proxy
        - python >=${{ python_min }}
        - setuptools <71.0.0
        - if: match(python_min, ">=3.12")
          then: pendulum >=3
        - if: match(python_min, "<3.12")
          then: pendulum
      run_constraints:
        - python ${{ python_min }}.*

    # newer python errors with:
    ##  >>> from airflow.hooks.base_hook import BaseHook
    ##  ModuleNotFoundError: No module named 'airflow.hooks.base_hook'
    # apache-airflow-providers-fab 2.4.4 has requirement apache-airflow>=3.0.2, but you have apache-airflow 2.11.0.
    tests:
      - package_contents:
          strict: true
          site_packages:
            - dagster_airflow/**
            - dagster_airflow-${{ version }}.dist-info/**
      - if: not match(python_min, ">=3.13")
        then:
          requirements:
            run:
              - pip
              - airflow <3
              - apache-airflow-providers-fab <2
              - python ${{ python_min }}.*
          script:
            - pip check
            - python -c "import dagster_airflow"
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow
      license: Apache-2.0
      license_file: LICENSE
      summary: Airflow plugin for Dagster

about:
  homepage: https://github.com/dagster-io
  summary: The data orchestration platform built for productivity.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://dagster.readthedocs.io
  description: >-
    Dagster is a system for building modern data applications. Combining an elegant programming model and beautiful tools, Dagster allows infrastructure engineers, data engineers, and data scientists to seamlessly collaborate to process and produce the trusted, reliable data needed in today's world.

extra:
  feedstock-name: dagster
  recipe-maintainers:
    - xhochy
    - bollwyvl
    - mgasner
