# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  # source-of-truth
  version: "1.12.3"
  # convenience
  pip_install: -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

recipe:
  name: dagster-meta
  version: ${{ version }}

build:
  noarch: python
  number: 0

outputs:
  # deps of dagster
  - package:
      name: dagster-pipes
    source:
      url: https://pypi.org/packages/source/d/dagster-pipes/dagster_pipes-${{ version }}.tar.gz
      sha256: 7720b0495518dd58dc1bfa1a12796aa3ced9d2d5f8158c695b5432248dec4ed5
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_pipes
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-pipes
      license: Apache-2.0
      license_file: LICENSE
      summary: Toolkit for Dagster integrations with transform logic outside of Dagster

  - package:
      name: dagster-shared
    source:
      url: https://pypi.org/packages/source/d/dagster-shared/dagster_shared-${{ version }}.tar.gz
      sha256: 4a7a0c7ce08db9a14606a56eb7be0358024f4ba0b63982fd8254e711bd3f862e
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - click
        - packaging >=20.9
        - platformdirs
        - pydantic >=2,<3.0.0
        - python >=${{ python_min }}
        - pyyaml >=5.1
        - tomlkit
        - typing_extensions >=4.11.0,<5
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_shared
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/librariees/dagster-shared
      license: Apache-2.0
      license_file: LICENSE
      summary: Shared code between dagster and dagster-dg.

  # dagster itself
  - package:
      name: dagster
    source:
      url: https://pypi.org/packages/source/d/dagster/dagster-${{ version }}.tar.gz
      sha256: 990dcc645671b57b2ba19771dbb79c7177e3b7279ae1952ae7ebf832ea9cf8c9
    build:
      number: 0
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster = dagster.cli:main
          - dagster-daemon = dagster.daemon.cli:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - if: python_min in ["3.12", "3.13"]
          then: universal_pathlib >=0.2.0
          else: universal_pathlib
        - if: python_min in ["3.11", "3.12", "3.13"]
          then: protobuf >=4,<7
          else: protobuf >=3.20.0,<7
        - ${{ pin_subpackage("dagster-pipes", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - alembic >=1.2.1,!=1.6.3,!=1.7.0,!=1.11.0
        - antlr-python-runtime
        - click >=5.0,<9.0
        - coloredlogs >=6.1,<=14.0
        - docstring_parser
        - filelock
        - grpcio >=1.44.0
        - grpcio-health-checking >=1.44.0
        - jinja2
        - psutil >=1.0
        - python >=${{ python_min }}
        - python-dotenv
        - python-tzdata
        - pytz
        - pywin32-on-windows
        - requests
        - rich
        - setuptools
        - six
        - sqlalchemy >=1.0,<3
        - structlog
        - tabulate
        - tomli <3
        - toposort >=1.0
        - tqdm <5
        - watchdog >=0.8.3,<7
      run_constraints:
        - python ${{ python_min }}.*
        - pywin32 !=226
    tests:
      - python:
          imports:
            - dagster
            - dagster.api
            - dagster.check
            - dagster.cli
            - dagster.config
            - dagster.core.definitions
            - dagster.core.events
            - dagster.core.execution
            - dagster.core.executor
            - dagster.core.instance
            - dagster.core.launcher
            - dagster.core.run_coordinator
            - dagster.core.scheduler
            - dagster.core.selector
            - dagster.core.snap
            - dagster.core.storage
            - dagster.core.system_config
            - dagster.core.types
            - dagster.core.workspace
            - dagster.daemon
            - dagster.grpc
            - dagster.loggers
            - dagster.seven
            - dagster.utils
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dagster --help
          - dagster-daemon --help
    about:
      homepage: https://github.com/dagster-io/dagster
      license: Apache-2.0
      summary: The data orchestration platform built for productivity.
      documentation: https://dagster.readthedocs.io
      license_file: LICENSE
      description: |
        Dagster lets you define pipelines in terms of the data flow between reusable, logical components,
        then test locally and run anywhere. With a unified view of pipelines and the assets they produce,
        Dagster can schedule and orchestrate Pandas, Spark, SQL, or anything else that Python can invoke.

        Dagster is designed for data platform engineers, data engineers, and full-stack data scientists.
        Building a data platform with Dagster makes your stakeholders more independent and your systems
        more robust. Developing data pipelines with Dagster makes testing easier and deploying faster.

  # other things that use the main `version`
  - package:
      name: create-dagster
    source:
      url: https://pypi.org/packages/source/c/create-dagster/create_dagster-${{ version }}.tar.gz
      sha256: f5b7cb03710171958a7953b663db6885f9a84179cf73ab87e65d827cc57ee332
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - create-dagster = create_dagster.cli:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: create_dagster
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - create-dagster --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/create-dagster
      license: Apache-2.0
      license_file: LICENSE
      summary: CLI for creating a new dg project or workspace.

  - package:
      name: dagster-cloud-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-cloud-cli/dagster_cloud_cli-${{ version }}.tar.gz
      sha256: 52162630aa944958dd731157cfaca18c667bc09399fd58cd6817fe1d205cbbc0
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-cloud = dagster_cloud_cli.entrypoint:app
          - dagster-plus = dagster_cloud_cli.entrypoint:app
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click
        - github3.py
        - jinja2
        - packaging >=20.9
        - python >=${{ python_min }}
        - pyyaml >=5.1
        - questionary
        - requests
        - setuptools
        - tomli >=1.1.0
        - typer >=0.4.1
        - validators
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_cloud_cli
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagster-cloud --help
          - dagster-plus --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-cloud-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Command line interface for Dagster Cloud

  - package:
      name: dagster-dg-cli
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-cli/dagster_dg_cli-${{ version }}.tar.gz
      sha256: e6447c547a60974fea3b2ea3cd3fef54d537ac3a22c38bb9371b54aac6afcb82
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dg = dagster_dg_cli.cli:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-dg-core", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
        - typer
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_dg_cli
          pip_check: true
          python_version: ${{ python_min }}.*
      - script:
          - dg --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-cli
      license: Apache-2.0
      license_file: LICENSE
      summary: Experimental API for scaffolding Dagster projects and components. Includes the dg CLI tool.

  - package:
      name: dagster-dg-core
    source:
      url: https://pypi.org/packages/source/d/dagster-dg-core/dagster_dg_core-${{ version }}.tar.gz
      sha256: 72342d952f0f0562bf01c867a30d2675258a66e9e3d77282e03c83248741a479
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-cloud-cli", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster-shared", upper_bound="x.x.x") }}
        - click >=8,<9
        - click-aliases
        - gql-with-requests
        - jinja2
        - jsonschema
        - markdown
        - packaging
        - python >=${{ python_min }}
        - python-dotenv
        - pyyaml >=5.1
        - rich
        - setuptools
        - tomlkit <0.13.3
        - typer <0.17.0
        - typing_extensions >=4.4.0,<5
        - watchdog
        - yaspin
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_dg_core
          pip_check: true
          python_version: ${{ python_min }}.*
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-dg-core
      license: Apache-2.0
      license_file: LICENSE
      summary: Core libraries for the dagster-dg-cli and create-dagster packages.

  - package:
      name: dagster-graphql
    source:
      url: https://pypi.org/packages/source/d/dagster-graphql/dagster_graphql-${{ version }}.tar.gz
      sha256: ab93717d1c9b3661ed8809ee15ed7356c7b0f4a0c4acf205de0987f999b12a1b
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-graphql = dagster_graphql.cli:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - gql-with-requests >=3.0.0,<4.0.0
        - graphene >=3,<4
        - python >=${{ python_min }}
        - requests
        - starlette
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports:
            - dagster_graphql
            - dagster_graphql.client
            - dagster_graphql.schema
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagster-graphql --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-graphql
      license: Apache-2.0
      license_file: LICENSE
      summary: The GraphQL frontend to python dagster.

  - package:
      name: dagster-webserver
    source:
      url: https://pypi.org/packages/source/d/dagster-webserver/dagster_webserver-${{ version }}.tar.gz
      sha256: 60627f9c4efcf5ed2d92df8a5b84d0acebab971403503b256a7c3fa1e2038a62
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagster-webserver = dagster_webserver.cli:main
          - dagster-webserver-debug = dagster_webserver.debug:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-graphql", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - click >=7.0,<9.0
        - python >=${{ python_min }}
        - starlette !=0.36.0
        - uvicorn-standard
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagster_webserver
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagster-webserver --help
          - dagster-webserver-debug --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-webserver
      license: Apache-2.0
      license_file: LICENSE
      summary: Web UI for dagster.

  - package:
      name: dagit
    source:
      url: https://pypi.org/packages/source/d/dagit/dagit-${{ version }}.tar.gz
      sha256: 071c9e49f753a11e1fe4a489c8d7a4e418fb5d2666b87ad9469e458b54efb538
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
      python:
        entry_points:
          - dagit = dagster_webserver.cli:main
          - dagit-debug = dagster_webserver.debug:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster-webserver", upper_bound="x.x.x") }}
        - python >=${{ python_min }}
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      - python:
          imports: dagit
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - dagit --help
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagit
      license: Apache-2.0
      license_file: LICENSE
      summary: Dagster UI

  - package:
      name: dagster-airflow
    source:
      url: https://pypi.org/packages/source/d/dagster-airflow/dagster_airflow-${{ version }}.tar.gz
      sha256: e265fb81f4b8b206bf57a4466adaedee9f90b4eb18429e3a84861c3d5e43353c
    build:
      noarch: python
      script: ${{ PYTHON }} ${{ pip_install }}
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - ${{ pin_subpackage("dagster", upper_bound="x.x.x") }}
        - lazy-object-proxy
        - pendulum
        - python >=${{ python_min }}
        - setuptools <71.0.0
      run_constraints:
        - python ${{ python_min }}.*
    tests:
      # not-yet-available-on-conda-forge
      - if: python_min not in ["3.13"]
        then:
          requirements:
            run:
              - pip
              # errors with:
              ##  >>> from airflow.hooks.base_hook import BaseHook
              ##  ModuleNotFoundError: No module named 'airflow.hooks.base_hook'
              - airflow <3
              - python ${{ python_min }}.*
          script:
            - pip check
            - python -c "import dagster_airflow"
    about:
      homepage: https://github.com/dagster-io/dagster/tree/master/python_modules/dagster-airflow
      license: Apache-2.0
      license_file: LICENSE
      summary: Airflow plugin for Dagster

about:
  homepage: https://github.com/dagster-io
  summary: The data orchestration platform built for productivity.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://dagster.readthedocs.io
  description: >-
    Dagster is a system for building modern data applications. Combining an elegant programming model and beautiful tools, Dagster allows infrastructure engineers, data engineers, and data scientists to seamlessly collaborate to process and produce the trusted, reliable data needed in today's world.

extra:
  feedstock-name: dagster
  recipe-maintainers:
    - xhochy
    - bollwyvl
    - mgasner
