# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "dagster-feedstock"
version = "3.52.3"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/dagster-feedstock"
authors = ["@conda-forge/dagster"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "!=0.49.0"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build dagster-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_python_min3.10"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python_min3.10.yaml"
description = "Build dagster-feedstock with variant linux_64_python_min3.10 directly (without setup scripts)"
[tasks."inspect-linux_64_python_min3.10"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python_min3.10.yaml"
description = "List contents of dagster-feedstock packages built for variant linux_64_python_min3.10"
[tasks."build-linux_64_python_min3.11"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python_min3.11.yaml"
description = "Build dagster-feedstock with variant linux_64_python_min3.11 directly (without setup scripts)"
[tasks."inspect-linux_64_python_min3.11"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python_min3.11.yaml"
description = "List contents of dagster-feedstock packages built for variant linux_64_python_min3.11"
[tasks."build-linux_64_python_min3.12"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python_min3.12.yaml"
description = "Build dagster-feedstock with variant linux_64_python_min3.12 directly (without setup scripts)"
[tasks."inspect-linux_64_python_min3.12"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python_min3.12.yaml"
description = "List contents of dagster-feedstock packages built for variant linux_64_python_min3.12"
[tasks."build-linux_64_python_min3.13"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_python_min3.13.yaml"
description = "Build dagster-feedstock with variant linux_64_python_min3.13 directly (without setup scripts)"
[tasks."inspect-linux_64_python_min3.13"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_python_min3.13.yaml"
description = "List contents of dagster-feedstock packages built for variant linux_64_python_min3.13"

[feature.smithy.dependencies]
conda-smithy = "*"
shellcheck = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
